package CapaDePresentacion;

import Modelo.MateriaPrima;
import ReglasDeNegocio.GestorMateriaPrima;
import ReglasDeNegocio.GestorProveedor;
import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author LucianoHorvath
 */
public class ABMMateriaPrima extends javax.swing.JDialog {

    private static int operacion;
    private static int idMp;
    private static GestorMateriaPrima gestor;
    private static GestorProveedor gestorProveedor;
    
    /**Este constructor no incluye idMateriaPrima porque es el que se invoca al hacer un Alta,
     * y el id lo pone la base de datos (es un autonumérico).
     * @param op la operación que se quiere realizar. 1-Alta, 2-Modificación, 3-Baja.
     * @param gestor para comunicarse con el DAO.
     * @param gestorP gestor proveedor necesario comunicarse con el DAO al agregar proveedores.
     */
    public ABMMateriaPrima(int op, GestorMateriaPrima gestor, GestorProveedor gestorP) {   
        initComponents();                                         
        inicializaciones(op, gestor);
        ABMMateriaPrima.gestorProveedor = gestorP;
        modificarVentana(operacion);
    }
    
    /**Constructor para bajas y modificaciones.
     * 
     * @param op la operación que se quiere realizar. 1-Alta, 2-Modificación, 3-Baja.
     * @param gestor para comunicarse con el DAO.
     * @param idMp el id de la materia prima que se quiere modificar/eliminar.
     * @param padre el JDialog padre.
     */
    public ABMMateriaPrima(int op, GestorMateriaPrima gestor, int idMp, JDialog padre) {
        super(padre, true);
        initComponents();
        inicializaciones(op, gestor);
        ABMMateriaPrima.idMp = idMp;
        modificarVentana(operacion);
    }

    private void inicializaciones(int op, GestorMateriaPrima gestor){
        operacion = op;   
        ABMMateriaPrima.gestor = gestor;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        jLIdPt = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLDescripcion = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jLStockCritico = new javax.swing.JLabel();
        jTextStockCritico = new javax.swing.JFormattedTextField();
        jLProveedores = new javax.swing.JLabel();
        jTextProveedores = new javax.swing.JTextField();
        jBAgregarProveedor = new javax.swing.JButton();
        jPanelBotonesSuperpuestos = new javax.swing.JPanel();
        jBAlta = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBBaja = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM de Materia Prima");

        jPanelDatos.setPreferredSize(new java.awt.Dimension(300, 120));

        jLIdPt.setText("ID Producto Terminado:");
        jLIdPt.setPreferredSize(new java.awt.Dimension(150, 27));

        jTextId.setEnabled(false);
        jTextId.setPreferredSize(new java.awt.Dimension(130, 27));
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });

        jLDescripcion.setText("Descripción:");
        jLDescripcion.setPreferredSize(new java.awt.Dimension(150, 27));

        jTextDescripcion.setPreferredSize(new java.awt.Dimension(130, 27));
        jTextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionActionPerformed(evt);
            }
        });

        jLStockCritico.setText("Stock crítico:");
        jLStockCritico.setPreferredSize(new java.awt.Dimension(150, 27));

        jTextStockCritico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        jTextStockCritico.setToolTipText("Sólo valores positivos.");
        jTextStockCritico.setMinimumSize(new java.awt.Dimension(130, 27));
        jTextStockCritico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStockCriticoActionPerformed(evt);
            }
        });

        jLProveedores.setText("Proveedores:");
        jLProveedores.setPreferredSize(new java.awt.Dimension(150, 27));

        jTextProveedores.setPreferredSize(new java.awt.Dimension(130, 27));
        jTextProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextProveedoresActionPerformed(evt);
            }
        });

        jBAgregarProveedor.setText("Agregar proveedor...");
        jBAgregarProveedor.setPreferredSize(new java.awt.Dimension(160, 27));
        jBAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jLProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosLayout.createSequentialGroup()
                                .addComponent(jLStockCritico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextStockCritico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanelDatosLayout.createSequentialGroup()
                            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextDescripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelDatosLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jBAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStockCritico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextStockCritico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBAgregarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanelBotonesSuperpuestos.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanelBotonesSuperpuestos.setLayout(null);

        jBAlta.setText("Dar de alta");
        jBAlta.setAlignmentY(0.0F);
        jBAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAlta.setPreferredSize(new java.awt.Dimension(100, 27));
        jBAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAltaActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBAlta);
        jBAlta.setBounds(0, 10, 100, 27);

        jBModificar.setText("Modificar");
        jBModificar.setAlignmentY(0.0F);
        jBModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBModificar);
        jBModificar.setBounds(0, 10, 95, 27);

        jBBaja.setText("Dar de baja");
        jBBaja.setAlignmentY(0.0F);
        jBBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBajaActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBBaja);
        jBBaja.setBounds(0, 10, 95, 27);

        jBCancelar.setText("Cancelar");
        jBCancelar.setPreferredSize(new java.awt.Dimension(100, 27));
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBCancelar);
        jBCancelar.setBounds(125, 10, 100, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanelBotonesSuperpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBotonesSuperpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionActionPerformed
        realizarOperacion(evt);
    }//GEN-LAST:event_jTextDescripcionActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jBBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBajaActionPerformed
        String mensaje;
                
        if (gestor.darBajaMp(idMp) == 1)
            mensaje = "Materia prima eliminada con éxito.";
        else
            mensaje = "Error al eliminar la materia prima.";
        
        System.out.println(mensaje);        
        JOptionPane.showMessageDialog(this, mensaje);
        this.dispose();
    }//GEN-LAST:event_jBBajaActionPerformed

    private void jBAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAltaActionPerformed
        String mensaje;
        String descripcion = jTextDescripcion.getText();
        
        //la validación de que la descripción no exista ya en la bdd la hará la bdd
        //(hay que manejar la excepción)
          
        
        if ((gestor.darAltaMp(descripcion) == 1))
            mensaje = "Datos insertados con éxito.";
        else
            mensaje = "Error al insertar los datos.";

        System.out.println(mensaje);        
        JOptionPane.showMessageDialog(this, mensaje);   

        limpiaPanelDatos();
    }//GEN-LAST:event_jBAltaActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        String mensaje;
                
        if (gestor.modificarMp(levantarDatos()) == 1)
            mensaje = "Datos modificados con éxito.";
        else
            mensaje = "Error al modificar los datos.";
        
        System.out.println(mensaje);        
        JOptionPane.showMessageDialog(this, mensaje);
        this.dispose();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void jTextProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextProveedoresActionPerformed

    private void jTextStockCriticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextStockCriticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextStockCriticoActionPerformed

    private void jBAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarProveedorActionPerformed
        VerProveedores verProv = new VerProveedores(5, gestorProveedor, this);        
        verProv.setVisible(true);
        
        jTextProveedores.setText(Integer.toString(verProv.getIdProveedor()));
    }//GEN-LAST:event_jBAgregarProveedorActionPerformed

    private void modificarVentana(int operacion){
        modificarBotones(operacion);
        
        switch(operacion){
            case 2: {
                mostrarDatosMp(idMp);
                break;
            }    
            case 3:{
                mostrarDatosMp(idMp);
                deshabilitarPanelDatos();
                break;
            }
        }
    }    
      
    private void deshabilitarPanelDatos(){
        Component[] listaComponentes = jPanelDatos.getComponents();
        
        for (Component c: listaComponentes)
            c.setEnabled(false);
    }
    
    private void limpiaPanelDatos(){
        Component[] listaComponentes = jPanelDatos.getComponents();
        
        for (Component c: listaComponentes)
            if (c instanceof JTextField)
              ((JTextField) c).setText("");
    }
        
    /**
    * Este método modifica la visibilidad de los botones de la ventana,
    * presentando el que corresponda según el parámetro recibido.
    *
    * @param operacion 1 para alta, 2 para modificación, 3 para baja.
    */
    private void modificarBotones(int operacion){
        switch (operacion){
            case 1: {
                    this.jBAlta.setVisible(true);
                    this.jBBaja.setVisible(false);
                    this.jBModificar.setVisible(false);
                    break;}
            case 2: {
                    this.jBAlta.setVisible(false);
                    this.jBModificar.setVisible(true);
                    this.jBBaja.setVisible(false);
                    break;}
            case 3:{
                    this.jBAlta.setVisible(false);
                    this.jBModificar.setVisible(false);
                    this.jBBaja.setVisible(true);
                    break;}
        }
    }
    
    private void mostrarDatosMp(int idMp){
        MateriaPrima mp = gestor.traerMp(idMp);
        
        jTextId.setText(Integer.toString(idMp));
        jTextDescripcion.setText(mp.getDescripcion());
        jTextStockCritico.setText(Integer.toString(mp.getStockCritico()));
        jTextProveedores.setText("");
    }
          
    private MateriaPrima levantarDatos(){                
        MateriaPrima mp = new MateriaPrima();
        
        mp.setId(Integer.valueOf(jTextId.getText()));
        mp.setDescripcion(jTextDescripcion.getText());
         
        return mp;
    }
    
    /**
    * Realiza la operación correspondiente (A,B,M). El método se utiliza al presionar enter 
    * en un campo de texto, como alternativa a hacer click en el botón A/B/M.
    */
    private void realizarOperacion(ActionEvent evt) {
                
        switch(operacion){
            case 1: jBAltaActionPerformed(evt);
                    break;
            case 2: jBModificarActionPerformed(evt);
                    break;
            case 3: jBBajaActionPerformed(evt);
                    break;
        }
    }
    
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMMateriaPrima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMMateriaPrima(operacion, gestor, gestorProveedor).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarProveedor;
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBBaja;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLIdPt;
    private javax.swing.JLabel jLProveedores;
    private javax.swing.JLabel jLStockCritico;
    private javax.swing.JPanel jPanelBotonesSuperpuestos;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextProveedores;
    private javax.swing.JFormattedTextField jTextStockCritico;
    // End of variables declaration//GEN-END:variables


}
