package CapaDePresentacion;

import ReglasDeNegocio.GestorProductoTerminado;
import Modelo.ProductoTerminado;
import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author LucianoHorvath
 */
public class ABMProductoTerminado extends javax.swing.JDialog {

    private static int operacion;
    private static int idPt;
    private static GestorProductoTerminado gestor;
    
    /**Este constructor no incluye idProductoTerminado porque es el que se invoca al hacer un Alta,
     * y el id lo pone la base de datos (es un autonumérico).
     * @param op la operación que se quiere realizar. 1-Alta, 2-Modificación, 3-Baja.
     * @param gestor 
     */
    public ABMProductoTerminado(int op, GestorProductoTerminado gestor) {   
        initComponents();                                         
        operacion = op;   
        ABMProductoTerminado.gestor = gestor;
        modificarVentana(operacion);
    }
    
    /**Este constructor se utiliza al modificar o dar de baja un producto terminado, ya que se 
     * llama desde VerProductosTerminados y debe ser modal a ésta.
     * 
     * @param op 2 para Modificación, 3 para baja.
     * @param gestor
     * @param idPt el id del Producto Terminado en cuestión.
     * @param padre el JFrame padre.
     */
    public ABMProductoTerminado(int op, GestorProductoTerminado gestor, int idPt, javax.swing.JFrame padre) {
        super(padre, true);
        initComponents();
        operacion = op;
        ABMProductoTerminado.gestor = gestor;
        ABMProductoTerminado.idPt = idPt;
        modificarVentana(operacion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBotonesSuperpuestos = new javax.swing.JPanel();
        jBAlta = new javax.swing.JButton();
        jBModificar = new javax.swing.JButton();
        jBBaja = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLIdPt = new javax.swing.JLabel();
        jTextId = new javax.swing.JTextField();
        jLDescripcion = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ABM de productos terminados");
        setPreferredSize(new java.awt.Dimension(340, 180));

        jPanelBotonesSuperpuestos.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanelBotonesSuperpuestos.setLayout(null);

        jBAlta.setText("Dar de alta");
        jBAlta.setAlignmentY(0.0F);
        jBAlta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAltaActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBAlta);
        jBAlta.setBounds(0, 10, 95, 27);

        jBModificar.setText("Modificar");
        jBModificar.setAlignmentY(0.0F);
        jBModificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBModificar);
        jBModificar.setBounds(0, 10, 95, 27);

        jBBaja.setText("Dar de baja");
        jBBaja.setAlignmentY(0.0F);
        jBBaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBajaActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBBaja);
        jBBaja.setBounds(0, 10, 95, 27);

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanelBotonesSuperpuestos.add(jBCancelar);
        jBCancelar.setBounds(125, 10, 90, 27);

        jPanelDatos.setPreferredSize(new java.awt.Dimension(300, 120));

        jLIdPt.setText("ID Producto Terminado:");
        jLIdPt.setPreferredSize(new java.awt.Dimension(70, 20));

        jTextId.setEnabled(false);
        jTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdActionPerformed(evt);
            }
        });

        jLDescripcion.setText("Descripción:");
        jLDescripcion.setPreferredSize(new java.awt.Dimension(85, 20));

        jTextDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLIdPt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextId)
                    .addComponent(jTextDescripcion)))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanelBotonesSuperpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotonesSuperpuestos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTextDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionActionPerformed
        realizarOperacion(evt);
    }//GEN-LAST:event_jTextDescripcionActionPerformed

    private void jTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdActionPerformed

    private void jBBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBajaActionPerformed
        String mensaje;
                
        if (gestor.darBajaPt(idPt) == 1)
            mensaje = "Producto terminado eliminado con éxito.";
        else
            mensaje = "Error al eliminar el producto terminado.";
        
        System.out.println(mensaje);        
        JOptionPane.showMessageDialog(this, mensaje);
        this.dispose();
    }//GEN-LAST:event_jBBajaActionPerformed

    private void jBAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAltaActionPerformed
        String mensaje;
        String descripcion = jTextDescripcion.getText();
        
        //la validación de que la descripción no exista ya en la bdd la hará la bdd
        //(hay que manejar la excepción)
          
        
        if ((gestor.darAltaPt(descripcion) == 1))
            mensaje = "Datos insertados con éxito.";
        else
            mensaje = "Error al insertar los datos.";

        System.out.println(mensaje);        
        JOptionPane.showMessageDialog(this, mensaje);   

        limpiaPanelDatos();
    }//GEN-LAST:event_jBAltaActionPerformed

    private void jBModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarActionPerformed
        String mensaje;
                
        if (gestor.modificarPt(levantarDatos()) == 1)
            mensaje = "Datos modificados con éxito.";
        else
            mensaje = "Error al modificar los datos.";
        
        System.out.println(mensaje);        
        JOptionPane.showMessageDialog(this, mensaje);
        this.dispose();
    }//GEN-LAST:event_jBModificarActionPerformed

    private void modificarVentana(int operacion){
        modificarBotones(operacion);
        
        switch(operacion){
            case 2: {
                mostrarDatosPt(idPt);
                break;
            }    
            case 3:{
                mostrarDatosPt(idPt);
                deshabilitarPanelDatos();
                break;
            }
        }
    }    
      
    private void deshabilitarPanelDatos(){
        Component[] listaComponentes = jPanelDatos.getComponents();
        
        for (Component c: listaComponentes)
            c.setEnabled(false);
    }
    
    private void limpiaPanelDatos(){
        Component[] listaComponentes = jPanelDatos.getComponents();
        
        for (Component c: listaComponentes)
            if (c instanceof JTextField)
              ((JTextField) c).setText("");
    }
        
    /**
    * Este método modifica la visibilidad de los botones de la ventana,
    * presentando el que corresponda según el parámetro recibido.
    *
    * @param operacion 1 para alta, 2 para modificación, 3 para baja.
    */
    private void modificarBotones(int operacion){
        switch (operacion){
            case 1: {
                    this.jBAlta.setVisible(true);
                    this.jBBaja.setVisible(false);
                    this.jBModificar.setVisible(false);
                    break;}
            case 2: {
                    this.jBAlta.setVisible(false);
                    this.jBModificar.setVisible(true);
                    this.jBBaja.setVisible(false);
                    break;}
            case 3:{
                    this.jBAlta.setVisible(false);
                    this.jBModificar.setVisible(false);
                    this.jBBaja.setVisible(true);
                    break;}
        }
    }
    
    private void mostrarDatosPt(int idPt){
        ProductoTerminado pt = gestor.traerPt(idPt);
        
        jTextId.setText(Integer.toString(idPt));
        jTextDescripcion.setText(pt.getDescripcion());
    }
          
    private ProductoTerminado levantarDatos(){                
        ProductoTerminado pt = new ProductoTerminado();
        
        pt.setId(Integer.valueOf(jTextId.getText()));
        pt.setDescripcion(jTextDescripcion.getText());
         
        return pt;
    }
    
    /**
    * Realiza la operación correspondiente (A,B,M). El método se utiliza al presionar enter 
    * en un campo de texto, como alternativa a hacer click en el botón A/B/M.
    */
    private void realizarOperacion(ActionEvent evt) {
                
        switch(operacion){
            case 1: jBAltaActionPerformed(evt);
                    break;
            case 2: jBModificarActionPerformed(evt);
                    break;
            case 3: jBBajaActionPerformed(evt);
                    break;
        }
    }
    
        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMProductoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMProductoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMProductoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMProductoTerminado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMProductoTerminado(operacion, gestor).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlta;
    private javax.swing.JButton jBBaja;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBModificar;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLIdPt;
    private javax.swing.JPanel jPanelBotonesSuperpuestos;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextId;
    // End of variables declaration//GEN-END:variables


}
