/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDePresentacion;

/**
 *
 * @author Luciano
 */
public class InformeRecepcionAlta extends javax.swing.JFrame {

    /**
     * Creates new form InformeRecepcionAlta
     */
    public InformeRecepcionAlta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelNroLoteInt = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelIdProv = new javax.swing.JLabel();
        jLabelRazonSocial = new javax.swing.JLabel();
        jLabelIdMp = new javax.swing.JLabel();
        jLabelMpDesc = new javax.swing.JLabel();
        jLabelNroRemitoProv = new javax.swing.JLabel();
        jLabelNroLoteProv = new javax.swing.JLabel();
        jTextNroLoteInt = new javax.swing.JTextField();
        jTextFecha = new javax.swing.JTextField();
        jTextIdProv = new javax.swing.JTextField();
        jTextRazonSocial = new javax.swing.JTextField();
        jTextIdMp = new javax.swing.JTextField();
        jTextDescMp = new javax.swing.JTextField();
        jTextNroRemito = new javax.swing.JTextField();
        jTextNroLoteProv = new javax.swing.JTextField();
        jBBuscarMp = new javax.swing.JButton();
        jBBuscarProv = new javax.swing.JButton();
        jBRegistrar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrar Informe de Recepción");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNroLoteInt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNroLoteInt.setText("Número de Lote Interno");
        jPanel1.add(jLabelNroLoteInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 183, 30));

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelFecha.setText("Fecha de recepción");
        jPanel1.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 183, 30));

        jLabelIdProv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIdProv.setText("ID Proveedor");
        jPanel1.add(jLabelIdProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 183, 30));

        jLabelRazonSocial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelRazonSocial.setText("Razón Social");
        jPanel1.add(jLabelRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 100, 30));

        jLabelIdMp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelIdMp.setText("ID Materia Prima");
        jPanel1.add(jLabelIdMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 183, 30));

        jLabelMpDesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelMpDesc.setText("Descripción");
        jPanel1.add(jLabelMpDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 100, 30));

        jLabelNroRemitoProv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNroRemitoProv.setText("Número de Remito del Proveedor");
        jPanel1.add(jLabelNroRemitoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        jLabelNroLoteProv.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNroLoteProv.setText("Número de Lote del Proveedor");
        jPanel1.add(jLabelNroLoteProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 183, 30));

        jTextNroLoteInt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNroLoteInt.setEnabled(false);
        jPanel1.add(jTextNroLoteInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 120, 30));

        jTextFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFecha.setEnabled(false);
        jPanel1.add(jTextFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 120, 30));
        jPanel1.add(jTextIdProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 120, 30));
        jPanel1.add(jTextRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 120, 30));
        jPanel1.add(jTextIdMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 120, 30));
        jPanel1.add(jTextDescMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 120, 30));
        jPanel1.add(jTextNroRemito, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 120, 30));
        jPanel1.add(jTextNroLoteProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 120, 30));

        jBBuscarMp.setText("Buscar en la lista");
        jPanel1.add(jBBuscarMp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 120, 30));

        jBBuscarProv.setText("Buscar en la lista");
        jBBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProvActionPerformed(evt);
            }
        });
        jPanel1.add(jBBuscarProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 120, 30));

        jBRegistrar.setText("Registrar");
        jPanel1.add(jBRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        jBCancelar.setText("Cancelar");
        jPanel1.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarProvActionPerformed
        VerProveedores verProv = new VerProveedores();
        verProv.setVisible(true);
        
        /*
        no se si llamarlo con constructor vacio o con operacion=4.
        verProveedores deberia tener otro boton que NO me lleve al ABM, 
        o el mismo boton fijandose si es la operacion 4... si lo es, va a un metodo especial
        si no lo es, sigue su camino comun (ABM)
        
        */
    }//GEN-LAST:event_jBBuscarProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformeRecepcionAlta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformeRecepcionAlta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscarMp;
    private javax.swing.JButton jBBuscarProv;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelIdMp;
    private javax.swing.JLabel jLabelIdProv;
    private javax.swing.JLabel jLabelMpDesc;
    private javax.swing.JLabel jLabelNroLoteInt;
    private javax.swing.JLabel jLabelNroLoteProv;
    private javax.swing.JLabel jLabelNroRemitoProv;
    private javax.swing.JLabel jLabelRazonSocial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextDescMp;
    private javax.swing.JTextField jTextFecha;
    private javax.swing.JTextField jTextIdMp;
    private javax.swing.JTextField jTextIdProv;
    private javax.swing.JTextField jTextNroLoteInt;
    private javax.swing.JTextField jTextNroLoteProv;
    private javax.swing.JTextField jTextNroRemito;
    private javax.swing.JTextField jTextRazonSocial;
    // End of variables declaration//GEN-END:variables
}
