/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDePresentacion;

/**
 *
 * @author Luciano
 */
public class Stock extends javax.swing.JFrame {

    /**
     * Creates new form Stock
     */
    public Stock() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jpMp = new javax.swing.JPanel();
        jLID = new javax.swing.JLabel();
        jLNombreMp = new javax.swing.JLabel();
        jTextIDMp = new javax.swing.JTextField();
        jTextNombreMp = new javax.swing.JTextField();
        jBAgregar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBDescontar = new javax.swing.JButton();
        jLCantidad = new javax.swing.JLabel();
        jTextCantidad = new javax.swing.JTextField();
        jLExplicacion1 = new javax.swing.JLabel();
        jLExplicacion2 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTableMp = new javax.swing.JTable();
        jpPt = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock");

        jTabbedPane.setPreferredSize(new java.awt.Dimension(640, 480));

        jpMp.setPreferredSize(new java.awt.Dimension(640, 480));

        jLID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLID.setLabelFor(jTextIDMp);
        jLID.setText("ID Materia prima:");
        jLID.setPreferredSize(new java.awt.Dimension(130, 25));

        jLNombreMp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNombreMp.setText("Nombre materia prima:");
        jLNombreMp.setPreferredSize(new java.awt.Dimension(130, 25));

        jTextIDMp.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextIDMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDMpActionPerformed(evt);
            }
        });

        jTextNombreMp.setPreferredSize(new java.awt.Dimension(110, 25));

        jBAgregar.setText("Agregar");

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBDescontar.setText("Descontar");

        jLCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLCantidad.setText("Cantidad:");
        jLCantidad.setPreferredSize(new java.awt.Dimension(130, 25));

        jTextCantidad.setPreferredSize(new java.awt.Dimension(110, 25));

        jLExplicacion1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLExplicacion1.setText("Ingrese el ID o el nombre de la materia prima y la cantidad que desea agregar/descontar de la misma.");

        jLExplicacion2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLExplicacion2.setText("Presione \"Buscar\" para filtrar la tabla de stock según un ID o un nombre.");

        jScrollPane.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane.setToolTipText("Tabla de stock existente de materias primas");
        jScrollPane.setName(""); // NOI18N

        jTableMp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMp.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTableMp);

        javax.swing.GroupLayout jpMpLayout = new javax.swing.GroupLayout(jpMp);
        jpMp.setLayout(jpMpLayout);
        jpMpLayout.setHorizontalGroup(
            jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMpLayout.createSequentialGroup()
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLExplicacion2)
                            .addComponent(jLExplicacion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane)))
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpMpLayout.createSequentialGroup()
                                .addComponent(jLID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextIDMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMpLayout.createSequentialGroup()
                                .addComponent(jLNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMpLayout.createSequentialGroup()
                                .addComponent(jLCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpMpLayout.createSequentialGroup()
                                .addComponent(jBAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(jBDescontar)
                                .addGap(18, 18, 18)
                                .addComponent(jBCancelar)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpMpLayout.setVerticalGroup(
            jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMpLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLExplicacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLExplicacion2)
                .addGap(18, 18, 18)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextIDMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBAgregar)
                    .addComponent(jBDescontar)
                    .addComponent(jBCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane.getAccessibleContext().setAccessibleName("");

        jTabbedPane.addTab("Materias primas", null, jpMp, "");

        jpPt.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout jpPtLayout = new javax.swing.GroupLayout(jpPt);
        jpPt.setLayout(jpPtLayout);
        jpPtLayout.setHorizontalGroup(
            jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        jpPtLayout.setVerticalGroup(
            jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Productos terminados", jpPt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIDMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDMpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDMpActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed
    
    public void mostrarPestanaPt(){
        this.jTabbedPane.setSelectedComponent(jpPt);     //también puede usarse setSelectedIndex(1)
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://dojLNombreMpcle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBDescontar;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLExplicacion1;
    private javax.swing.JLabel jLExplicacion2;
    private javax.swing.JLabel jLID;
    private javax.swing.JLabel jLNombreMp;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableMp;
    private javax.swing.JTextField jTextCantidad;
    private javax.swing.JTextField jTextIDMp;
    private javax.swing.JTextField jTextNombreMp;
    private javax.swing.JPanel jpMp;
    private javax.swing.JPanel jpPt;
    // End of variables declaration//GEN-END:variables
}
