package CapaDePresentacion;

import ReglasDeNegocio.GestorMateriaPrima;
import ReglasDeNegocio.GestorProductoTerminado;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Luciano
 */
public class Stock extends javax.swing.JFrame {

    private static GestorMateriaPrima gestorMp;
    private static GestorProductoTerminado gestorPt;

    public Stock(GestorMateriaPrima gestorMp, GestorProductoTerminado gestorPt) {
        initComponents();
        Stock.gestorMp = gestorMp;
        Stock.gestorPt = gestorPt;
        cargarTabla();        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jpMp = new javax.swing.JPanel();
        jLExplicacion1 = new javax.swing.JLabel();
        jLExplicacion2 = new javax.swing.JLabel();
        jLIdMp = new javax.swing.JLabel();
        jLNombreMp = new javax.swing.JLabel();
        jLCantidadMp = new javax.swing.JLabel();
        jTextIdMp = new javax.swing.JTextField();
        jTextNombreMp = new javax.swing.JTextField();
        jTextCantidadMp = new javax.swing.JTextField();
        jBBuscarMp = new javax.swing.JButton();
        jBAgregarMp = new javax.swing.JButton();
        jBCancelarMp = new javax.swing.JButton();
        jBDescontarMp = new javax.swing.JButton();
        jScrollPaneMp = new javax.swing.JScrollPane();
        jTableMp = new javax.swing.JTable();
        jpPt = new javax.swing.JPanel();
        jLExplicacion3 = new javax.swing.JLabel();
        jLExplicacion4 = new javax.swing.JLabel();
        jLIdPt = new javax.swing.JLabel();
        jLNombrePt = new javax.swing.JLabel();
        jLCantidadPt = new javax.swing.JLabel();
        jTextIdPt = new javax.swing.JTextField();
        jTextNombrePt = new javax.swing.JTextField();
        jTextCantidadPt = new javax.swing.JTextField();
        jBBuscarPt = new javax.swing.JButton();
        jBAgregarPt = new javax.swing.JButton();
        jBCancelarPt = new javax.swing.JButton();
        jBDescontarPt = new javax.swing.JButton();
        jScrollPanePt = new javax.swing.JScrollPane();
        jTablePt = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock");

        jTabbedPane.setPreferredSize(new java.awt.Dimension(640, 480));

        jpMp.setPreferredSize(new java.awt.Dimension(640, 480));

        jLExplicacion1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLExplicacion1.setText("Ingrese el ID o el nombre de la materia prima y la cantidad que desea agregar/descontar de la misma.");

        jLExplicacion2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLExplicacion2.setText("Presione \"Buscar\" para filtrar la tabla de stock según un ID o un nombre.");

        jLIdMp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLIdMp.setLabelFor(jTextIdMp);
        jLIdMp.setText("ID Materia prima:");
        jLIdMp.setPreferredSize(new java.awt.Dimension(130, 25));

        jLNombreMp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNombreMp.setText("Nombre:");
        jLNombreMp.setPreferredSize(new java.awt.Dimension(130, 25));

        jLCantidadMp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLCantidadMp.setText("Cantidad:");
        jLCantidadMp.setPreferredSize(new java.awt.Dimension(130, 25));

        jTextIdMp.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextIdMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdMpActionPerformed(evt);
            }
        });

        jTextNombreMp.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextNombreMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreMpActionPerformed(evt);
            }
        });

        jTextCantidadMp.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextCantidadMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantidadMpActionPerformed(evt);
            }
        });

        jBBuscarMp.setText("Buscar");
        jBBuscarMp.setPreferredSize(new java.awt.Dimension(90, 27));
        jBBuscarMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarMpActionPerformed(evt);
            }
        });

        jBAgregarMp.setText("Agregar");
        jBAgregarMp.setPreferredSize(new java.awt.Dimension(90, 27));
        jBAgregarMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarMpActionPerformed(evt);
            }
        });

        jBCancelarMp.setText("Cancelar");
        jBCancelarMp.setPreferredSize(new java.awt.Dimension(90, 27));
        jBCancelarMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarMpActionPerformed(evt);
            }
        });

        jBDescontarMp.setText("Descontar");
        jBDescontarMp.setPreferredSize(new java.awt.Dimension(90, 27));
        jBDescontarMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescontarMpActionPerformed(evt);
            }
        });

        jScrollPaneMp.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPaneMp.setToolTipText("Tabla de stock existente de materias primas");
        jScrollPaneMp.setName(""); // NOI18N

        jTableMp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stock", "Stock crítico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMp.getTableHeader().setReorderingAllowed(false);
        jScrollPaneMp.setViewportView(jTableMp);

        javax.swing.GroupLayout jpMpLayout = new javax.swing.GroupLayout(jpMp);
        jpMp.setLayout(jpMpLayout);
        jpMpLayout.setHorizontalGroup(
            jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMpLayout.createSequentialGroup()
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneMp, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpMpLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpMpLayout.createSequentialGroup()
                                    .addComponent(jLIdMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextIdMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpMpLayout.createSequentialGroup()
                                    .addComponent(jLNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpMpLayout.createSequentialGroup()
                                    .addComponent(jLCantidadMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextCantidadMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jpMpLayout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpMpLayout.createSequentialGroup()
                                    .addComponent(jBBuscarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBAgregarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBDescontarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBCancelarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLExplicacion2)
                                .addComponent(jLExplicacion1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMpLayout.setVerticalGroup(
            jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMpLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLExplicacion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLExplicacion2)
                .addGap(18, 18, 18)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLIdMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextIdMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextNombreMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCantidadMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpMpLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextCantidadMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jpMpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDescontarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelarMp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneMp, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPaneMp.getAccessibleContext().setAccessibleName("");

        jTabbedPane.addTab("Materias primas", null, jpMp, "");

        jpPt.setPreferredSize(new java.awt.Dimension(640, 480));

        jLExplicacion3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLExplicacion3.setText("Ingrese el ID o el nombre del prod. terminado y la cantidad que desea agregar/descontar del mismo.");

        jLExplicacion4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLExplicacion4.setText("Presione \"Buscar\" para filtrar la tabla de stock según un ID o un nombre.");

        jLIdPt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLIdPt.setLabelFor(jTextIdMp);
        jLIdPt.setText("ID Prod. terminado:");
        jLIdPt.setPreferredSize(new java.awt.Dimension(130, 25));

        jLNombrePt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLNombrePt.setText("Nombre:");
        jLNombrePt.setPreferredSize(new java.awt.Dimension(130, 25));

        jLCantidadPt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLCantidadPt.setText("Cantidad:");
        jLCantidadPt.setPreferredSize(new java.awt.Dimension(130, 25));

        jTextIdPt.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextIdPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdPtActionPerformed(evt);
            }
        });

        jTextNombrePt.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextNombrePt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombrePtActionPerformed(evt);
            }
        });

        jTextCantidadPt.setPreferredSize(new java.awt.Dimension(110, 25));
        jTextCantidadPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantidadPtActionPerformed(evt);
            }
        });

        jBBuscarPt.setText("Buscar");
        jBBuscarPt.setPreferredSize(new java.awt.Dimension(90, 27));
        jBBuscarPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarPtActionPerformed(evt);
            }
        });

        jBAgregarPt.setText("Agregar");
        jBAgregarPt.setPreferredSize(new java.awt.Dimension(90, 27));
        jBAgregarPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarPtActionPerformed(evt);
            }
        });

        jBCancelarPt.setText("Cancelar");
        jBCancelarPt.setPreferredSize(new java.awt.Dimension(90, 27));
        jBCancelarPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarPtActionPerformed(evt);
            }
        });

        jBDescontarPt.setText("Descontar");
        jBDescontarPt.setPreferredSize(new java.awt.Dimension(90, 27));
        jBDescontarPt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDescontarPtActionPerformed(evt);
            }
        });

        jScrollPanePt.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPanePt.setToolTipText("Tabla de stock existente de materias primas");
        jScrollPanePt.setName(""); // NOI18N

        jTablePt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Stock", "Stock crítico"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePt.getTableHeader().setReorderingAllowed(false);
        jScrollPanePt.setViewportView(jTablePt);

        javax.swing.GroupLayout jpPtLayout = new javax.swing.GroupLayout(jpPt);
        jpPt.setLayout(jpPtLayout);
        jpPtLayout.setHorizontalGroup(
            jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPtLayout.createSequentialGroup()
                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPtLayout.createSequentialGroup()
                        .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPtLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLExplicacion4)
                                    .addComponent(jLExplicacion3)
                                    .addGroup(jpPtLayout.createSequentialGroup()
                                        .addComponent(jBBuscarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBAgregarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBDescontarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBCancelarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpPtLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpPtLayout.createSequentialGroup()
                                        .addComponent(jLIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpPtLayout.createSequentialGroup()
                                        .addComponent(jLNombrePt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextNombrePt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpPtLayout.createSequentialGroup()
                                        .addComponent(jLCantidadPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextCantidadPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(jpPtLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPanePt)))
                .addContainerGap())
        );
        jpPtLayout.setVerticalGroup(
            jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPtLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLExplicacion3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLExplicacion4)
                .addGap(18, 18, 18)
                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPtLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextIdPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombrePt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPtLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextNombrePt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCantidadPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpPtLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jTextCantidadPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBAgregarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBDescontarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBCancelarPt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPanePt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Productos terminados", jpPt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextIdMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdMpActionPerformed
        jBBuscarMpActionPerformed(evt);
    }//GEN-LAST:event_jTextIdMpActionPerformed

    private void jBCancelarMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarMpActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarMpActionPerformed

    private void jTextIdPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdPtActionPerformed
        jBBuscarPtActionPerformed(evt);
    }//GEN-LAST:event_jTextIdPtActionPerformed

    private void jBCancelarPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarPtActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarPtActionPerformed

    private void jBAgregarMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarMpActionPerformed
        modificarStock(1,1);
    }//GEN-LAST:event_jBAgregarMpActionPerformed

    private void jBDescontarPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescontarPtActionPerformed
        modificarStock(-1,2);
    }//GEN-LAST:event_jBDescontarPtActionPerformed

    private void jBBuscarMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarMpActionPerformed
        if (jTextIdMp.getText().isEmpty() && jTextNombreMp.getText().isEmpty())
            cargarTabla();
        else
            cargarTabla(jTextIdMp.getText(), jTextNombreMp.getText());
    }//GEN-LAST:event_jBBuscarMpActionPerformed

    private void jBBuscarPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarPtActionPerformed
        if (jTextIdPt.getText().isEmpty() && jTextNombrePt.getText().isEmpty()) 
            cargarTabla();
        else            
            cargarTabla(jTextIdPt.getText(), jTextNombrePt.getText());
    }//GEN-LAST:event_jBBuscarPtActionPerformed

    private void jTextNombreMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreMpActionPerformed
        jBBuscarMpActionPerformed(evt);
    }//GEN-LAST:event_jTextNombreMpActionPerformed

    private void jTextNombrePtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombrePtActionPerformed
        jBBuscarPtActionPerformed(evt);
    }//GEN-LAST:event_jTextNombrePtActionPerformed

    private void jTextCantidadPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantidadPtActionPerformed
        jBAgregarPtActionPerformed(evt);
    }//GEN-LAST:event_jTextCantidadPtActionPerformed

    private void jTextCantidadMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantidadMpActionPerformed
        jBAgregarMpActionPerformed(evt);
    }//GEN-LAST:event_jTextCantidadMpActionPerformed

    private void jBAgregarPtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarPtActionPerformed
        modificarStock(1,2);
    }//GEN-LAST:event_jBAgregarPtActionPerformed

    private void jBDescontarMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDescontarMpActionPerformed
        modificarStock(-1,1);
    }//GEN-LAST:event_jBDescontarMpActionPerformed
    
    public void mostrarPestanaPt(){
        this.jTabbedPane.setSelectedComponent(jpPt);     //también puede usarse setSelectedIndex(1)
        cargarTabla();
    }
        
    /**Carga la tabla completa en la pestaña actual (Materia prima o producto terminado).
     * 
     */
    private void cargarTabla(){
        if (jTabbedPane.getSelectedComponent() == jpMp){
            DefaultTableModel modelo = (DefaultTableModel)jTableMp.getModel();   
            jTableMp.setModel(gestorMp.traerTablaMpConStock(modelo));            
        }
        else{
            DefaultTableModel modelo = (DefaultTableModel)jTablePt.getModel(); 
            jTablePt.setModel(gestorPt.traerTablaPtConStock(modelo));           
        }    
    }
    
    /**Carga la tabla en la pestaña actual con los parámetros coincidentes, al menos uno de ellos.
     * 
     * @param id el id del Producto (MP/PT) que se desea ver.
     * @param nombre el nombre del Producto (MP/PT) que se desea ver.
     */
    private void cargarTabla(String id, String nombre){
        if (jTabbedPane.getSelectedComponent() == jpMp){
            DefaultTableModel modelo = (DefaultTableModel)jTableMp.getModel();   
            jTableMp.setModel(gestorMp.traerTablaMpConStock(modelo, id, nombre));            
        }
        else{
            DefaultTableModel modelo = (DefaultTableModel)jTablePt.getModel(); 
            jTablePt.setModel(gestorPt.traerTablaPtConStock(modelo, id, nombre));
        }        
    }
    
    /**Agrega o descuenta stock según corresponda.
     * 
     * @param operacion 1 para agregar, -1 para descontar.
     * @param tipoProducto 1 para materia prima, 2 para para producto terminado.
     */
    private void modificarStock(int operacion, int tipoProducto){
        String mensaje;
        
        if (tipoProducto == 1){        
            int idMp = Integer.parseInt(jTextIdMp.getText());
            int cantidad = operacion * Integer.parseInt(jTextCantidadMp.getText());

            if (gestorMp.modificarStock(idMp, cantidad) == 1)
                mensaje = "El stock se modificó con éxito.";
            else
                mensaje = "No se pudo modificar el stock.";
        }
        else{
            int idPt = Integer.parseInt(jTextIdPt.getText());
            int cantidad = operacion * Integer.parseInt(jTextCantidadPt.getText());

            if (gestorPt.modificarStock(idPt, cantidad) == 1)
                mensaje = "El stock se modificó con éxito.";
            else
                mensaje = "No se pudo modificar el stock.";            
        }
                        
        cargarTabla();
        System.out.println(mensaje);
        JOptionPane.showMessageDialog(this, mensaje);    
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://dojLNombreMpcle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock(gestorMp, gestorPt).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarMp;
    private javax.swing.JButton jBAgregarPt;
    private javax.swing.JButton jBBuscarMp;
    private javax.swing.JButton jBBuscarPt;
    private javax.swing.JButton jBCancelarMp;
    private javax.swing.JButton jBCancelarPt;
    private javax.swing.JButton jBDescontarMp;
    private javax.swing.JButton jBDescontarPt;
    private javax.swing.JLabel jLCantidadMp;
    private javax.swing.JLabel jLCantidadPt;
    private javax.swing.JLabel jLExplicacion1;
    private javax.swing.JLabel jLExplicacion2;
    private javax.swing.JLabel jLExplicacion3;
    private javax.swing.JLabel jLExplicacion4;
    private javax.swing.JLabel jLIdMp;
    private javax.swing.JLabel jLIdPt;
    private javax.swing.JLabel jLNombreMp;
    private javax.swing.JLabel jLNombrePt;
    private javax.swing.JScrollPane jScrollPaneMp;
    private javax.swing.JScrollPane jScrollPanePt;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTableMp;
    private javax.swing.JTable jTablePt;
    private javax.swing.JTextField jTextCantidadMp;
    private javax.swing.JTextField jTextCantidadPt;
    private javax.swing.JTextField jTextIdMp;
    private javax.swing.JTextField jTextIdPt;
    private javax.swing.JTextField jTextNombreMp;
    private javax.swing.JTextField jTextNombrePt;
    private javax.swing.JPanel jpMp;
    private javax.swing.JPanel jpPt;
    // End of variables declaration//GEN-END:variables
}
