package CapaDePresentacion;

import ReglasDeNegocio.GestorProveedor;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

public class VerProveedores extends javax.swing.JDialog {

    private static int operacion;
    private static GestorProveedor gestor;
    private int idProveedor;
    private String razonSocial;
     
    /**Este constructor crea una ventana modal, para ser llamado desde InformeRecepción
     * 
     * @param op 4 si es llamado desde InformeRecepción.
     * @param gestor gestor encargado de comunicarse con el DAO.
     * @param padre el JFrame padre.      
     */
    public VerProveedores(int op, GestorProveedor gestor, JFrame padre){
        super(padre, true);
        initComponents();
        inicializaciones(op, gestor);
    }
    
    /**Este constructor se llama desde ABMMateriaPrima, ya que VerProveedores debe ser modal a ésta.
     * Difiere del anterior en recibir un JDialog como padre.
     * 
     * @param op 5 si es llamado desde ABM MateriaPrima.
     * @param gestor gestor encargado de comunicarse con el DAO.
     * @param padre el JDialog padre.
     */
    public VerProveedores(int op, GestorProveedor gestor, JDialog padre){
        super(padre, true);
        initComponents();
        inicializaciones(op, gestor);
    }
    
    /**Constructor común, llamado previamente a hacer una baja o una modificación de Proveedores.
     * 
     * @param op 2 para modificación, 3 para baja.
     * @param gestor gestor encargado de comunicarse con el DAO.
     */
    public VerProveedores(int op, GestorProveedor gestor) {
        initComponents();
        inicializaciones(op, gestor);
    }
    
    private void inicializaciones(int op, GestorProveedor gestor){
        operacion = op;
        VerProveedores.gestor = gestor;
        cargarTabla();
    }
        
    public int getIdProveedor() {
        return idProveedor;
    }

    public String getRazonSocial() {
        return razonSocial;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaProveedores = new javax.swing.JTable();
        jBSeleccionar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver lista de proveedores ");
        setLocation(new java.awt.Point(300, 150));
        setResizable(false);

        jTablaProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Proveedor", "RazonSocial", "CUIT", "Dirección", "Teléfono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablaProveedores);

        jBSeleccionar.setText("Seleccionar");
        jBSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSeleccionarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBSeleccionar)
                .addGap(54, 54, 54)
                .addComponent(jBCancelar)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSeleccionar)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    /**Si la operación es 2 o 3 (Modificación o baja) abre la ventana ABM, si es 4 guarda la razón 
     * social para luego pedirla desde InformeRecepción, si es 5 no entra al switch, solamente
     * guarda el idProveedor para luego pedirlo desde ABM Materia Prima.
     * 
     */    
    private void jBSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSeleccionarActionPerformed
        Object idSeleccionado = jTablaProveedores.getModel().getValueAt(jTablaProveedores.getSelectedRow(), 0);
        idProveedor = (int)idSeleccionado;
        
        switch (operacion){
            case 2:
            case 3:     
                ABMProveedores abmProv = new ABMProveedores(operacion, idProveedor, gestor);
                abmProv.setVisible(true);
                break;
            case 4: 
                Object rSocialSeleccionada = jTablaProveedores.getModel().getValueAt(jTablaProveedores.getSelectedRow(), 1);
                razonSocial = (String)rSocialSeleccionada;
                break;
        }       

        this.dispose();
    }//GEN-LAST:event_jBSeleccionarActionPerformed
    
    private void cargarTabla(){
        System.out.println ("Cargando la tabla de proveedores...");
        DefaultTableModel modelo = (DefaultTableModel)jTablaProveedores.getModel();    
        /*Lo casteo porque el modelo que se edita gráficamente es un TableModel y quiero obtener los nombres
        de las columnas y la cantidad de las mismas.
        Sino, tendria que crear un DefaultTableModel y darle forma (columnas, filas) mediante código. */
               
        jTablaProveedores.setModel(gestor.leerTablaProveedorYDevolverModelo(modelo));
    };
       
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerProveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerProveedores(operacion, gestor).setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaProveedores;
    // End of variables declaration//GEN-END:variables
}
